name: Deploy Medusa to ECS

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

      - name: Build Docker image with ECR tag
        run: |
          docker build -t ${{ secrets.ECR_REGISTRY }}/medusa-backend:latest .

      - name: Push to ECR
        run: |
          docker push ${{ secrets.ECR_REGISTRY }}/medusa-backend:latest

      - name: Force ECS service update
        run: |
          aws ecs update-service \
            --cluster medusa-cluster \
            --service medusa-service \
            --force-new-deployment
